[package]
name = "exercise"
version = "0.1.0"
authors = ["zhao.zhang <zhao.zhang@upai.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
